name: Running Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd app
          pytest -m "unit"

      - name: Run functional tests
        env: # Or as an environment variable
          PGURL: ${{ secrets.TEST_DB_URI }}
        run: |
          cd app
          pytest -m "functional and org"
