name: Running Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd app
          pytest -m "unit" --html=test/cover/unit.html

      - name: Run functional tests
        run: |
          cd app
          pytest -m "functional" --html=test/cover/functional.html
        env:
          PGURL: ${{ secrets.PGURL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          INIT_SQL: "../db/init.sql"
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/test/cover/*.html

